### ISSUE TITLE
暂无权限使用，请在 AI Studio 正确获取访问令牌(access tok

### ISSUE THREAD

**Issue by myboyliu** [PaddlePaddle/ERNIE-SDK#102]
暂无权限使用，请在 AI Studio 正确获取访问令牌(access tok，查了还有tokens
![image](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/assets/5858920/133f85a7-5cf4-4095-bbec-8cd0bf0ba464)

**Comment by Bobholamovic** [comment]
你好，请确认一下`api_type`是否设置为`"aistudio"`

**Comment by 111wukong** [comment]
> 你好，请确认一下`api_type`是否设置为`"aistudio"`

"<access-token-for-aistudio>"与"<access-token-for-yinian>"是同一个东西吗？

**Comment by 111wukong** [comment]
> 你好，请确认一下`api_type`是否设置为`"aistudio"`

"<access-token-for-aistudio>"与"<access-token-for-yinian>"是同一个东西吗？

**Comment by 111wukong** [comment]
> 你好，请确认一下`api_type`是否设置为`"aistudio"`

access-token-for-aistudio与access-token-for-yinian是同一个东西吗？

**Comment by itagan** [comment]
如果是使用4.0的话需要在ai studio星河社区聊天频道申请一下权限。以前是这样子

**Comment by itagan** [comment]
https://aistudio.baidu.com/community/channel/105
