### ISSUE TITLE
function_calling 目录中没有 gradio_demo.py这个文件

### ISSUE THREAD

**Issue by liuzhengcai** [PaddlePaddle/ERNIE-SDK#112]

**Comment by shiyutang** [comment]
如果要起gradio demo，可以在建立agent之后调用agent.launch_gradio_demo

**Comment by Bobholamovic** [comment]
你好，文档中存在错误，脚本的实际名称为`function_calling_demo.py`，我们已经在此PR修复：
https://github.com/PaddlePaddle/ERNIE-Bot-SDK/pull/121

**Comment by sijunhe** [comment]
问题已修复
