### ISSUE TITLE
REAMDE鉴权相关链接全部失效

### ISSUE THREAD

**Issue by SWHL** [PaddlePaddle/ERNIE-SDK#197]
在develop的[README](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/blob/52d23f4196b89b98f892969c6acb0b3b69425160/README.md)中鉴权相关文档链接均已失效。

**Comment by sijunhe** [comment]
您好。https://github.com/PaddlePaddle/ERNIE-Bot-SDK/tree/develop/erniebot 这个页面链接的https://github.com/PaddlePaddle/ERNIE-Bot-SDK/blob/develop/erniebot/docs/authentication.md 是ok的。

**Comment by SWHL** [comment]
你好，你给的链接打开也是404
![image](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/assets/28639377/1f6f05f2-3e89-4755-8edc-21e242f9ca0b)

我是想反馈一下这个问题，我自己可以找到有效链接位置的。

**Comment by Southpika** [comment]
感谢反馈～目前仓库的内容在调整当中～麻烦见谅

**Comment by sijunhe** [comment]
#241 已修复。多谢 @SWHL 反馈！
