### ISSUE TITLE
自己写了一个RUST SDK，有大佬愿意看看嘛哈哈哈

### ISSUE THREAD

**Issue by chenwanqq** [PaddlePaddle/ERNIE-SDK#323]
[erniebot-rs](https://github.com/chenwanqq/erniebot-rs)，欢迎各位大佬批评指正哈，v0.1版本还很不完善，文档基本等于没有

**Comment by sijunhe** [comment]
感谢贡献！已加入readme.md中 https://github.com/PaddlePaddle/ERNIE-SDK/pull/341
