### ISSUE TITLE
RemoteToolkit.from_url("http://127.0.0.1:8020")读取openapi.yaml成功，但解析时报错。

### ISSUE THREAD

**Issue by zhougx88** [PaddlePaddle/ERNIE-SDK#331]
通过FastAPI定义了接口，发布了.well-known/openapi.yaml。其中
"openapi": "3.1.0",
  "info": {
    "title": "FastAPI",
    "version": "0.1.0"
  },
......
      "HTTPValidationError": {
        "properties": {
          "detail": {
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            },
            "type": "array",
            "title": "Detail"
          }
        },
        "type": "object",
        "title": "HTTPValidationError"
      },
 
但通过RemoteToolkit.from_url("http://127.0.0.1:8020") 时报以下错误：

Traceback (most recent call last):
  File "/home/ernie/erniebot/4.py", line 114, in <module>
    toolkit = RemoteToolkit.from_url("http://127.0.0.1:8020")  # 必须存在：http://xxx.com/.well-known/openapi.yaml
  File "/home/ernie/lib/python3.10/site-packages/erniebot_agent/tools/remote_toolkit.py", line 305, in from_url
    toolkit = RemoteToolkit.from_openapi_dict(
  File "/home/ernie/lib/python3.10/site-packages/erniebot_agent/tools/remote_toolkit.py", line 185, in from_openapi_dict
    parameter_view = ToolParameterView.from_openapi_dict(schema)
  File "/home/ernie/lib/python3.10/site-packages/erniebot_agent/tools/schema.py", line 252, in from_openapi_dict
    field_type = python_type_from_json_type(field_dict)
  File "/home/ernie/lib/python3.10/site-packages/erniebot_agent/tools/schema.py", line 108, in python_type_from_json_type
    assert "type" in json_type_dict["items"], "<items> field must be defined when 'type'=array"
AssertionError: <items> field must be defined when 'type'=array

**Comment by itagan** [comment]
这个是有些问题。使用文心大模型插件案例，启动服务，再作为远程工具，打开链接可以访问到openapi.yaml，提示没找到或者是文件内容格式校验失败，可能是格式不符合

**Comment by zhougx88** [comment]
应该是无法解析 'type': 'array',时的参数：
{'items': {'$ref': '#/components/schemas/ValidationError'}, 'type': 'array', 'title': 'Detail'}
{'items': {'anyOf': [{'type': 'string'}, {'type': 'integer'}]}, 'type': 'array', 'title': 'Location'}

以上类型的参数应该如何解析？

**Comment by zhougx88** [comment]
我做了以下处理，就可以正常运行了，但我感觉不对
if( "$ref" in json_type_dict["items"]):
        json_type_value = json_type_dict["items"]["$ref"]
        return List[str]
    if( "anyOf" in json_type_dict["items"]):
        json_type_value = json_type_dict["items"]["anyOf"]
        return List[str]
