### ISSUE TITLE
字段命名拼写错误

### ISSUE THREAD

**Issue by itagan** [PaddlePaddle/ERNIE-SDK#334]
ouptut_type ==》output_type
![截屏2024-03-20 15 01 14](https://github.com/PaddlePaddle/ERNIE-SDK/assets/24641745/019b244f-572a-41ef-80cc-0f7ab6c0d8fb)

**Comment by sijunhe** [comment]
感谢指正，我们修一下~

**Comment by wj-Mcat** [comment]
fixed by https://github.com/PaddlePaddle/ERNIE-SDK/pull/339
