### ISSUE TITLE
APIError: token 已经用完毕，请充值后使用

### ISSUE THREAD

**Issue by SwordyLee** [PaddlePaddle/ERNIE-SDK#342]
![image](https://github.com/PaddlePaddle/ERNIE-SDK/assets/115516093/0316f64c-9f56-4888-90fd-6321ec063e43)
创建对话返回错误accesstoken已用完，token是刚在aistudio创建的
![image](https://github.com/PaddlePaddle/ERNIE-SDK/assets/115516093/8ec401f9-a6ed-4479-94e1-2ca918d21cae)

**Comment by w5688414** [comment]
可以看一下aistudio是否有token，例如：

![image](https://github.com/PaddlePaddle/ERNIE-SDK/assets/12107462/4232cdf5-cbc5-4002-91d5-04595a1684fc)

**Comment by SwordyLee** [comment]
试用的token到期了，感谢
