### ISSUE TITLE
调用文本转图像的demo出错

### ISSUE THREAD

**Issue by kuaizilh** [PaddlePaddle/ERNIE-SDK#38]
请教下，这个报错是啥原因？erniebot最新版本以及早点的版本都试过，一样的报错
python 版本：3.9.7，windows下。
示例程序：
`import erniebot

erniebot.api_type = "yinian"
erniebot.access_token = "***************"

response = erniebot.Image.create(model="ernie-vilg-v2", prompt="请帮我画一只可爱的大猫咪", width=512, height=512, version="v2", image_num=1)

print(response)

img_url = response["data"]["sub_task_result_list"][0]["final_image_list"][0]["img_url"]
print(img_url)
print(response)`

运行时报错：
Exception has occurred: HTTPRequestError
Unexpected content type: 'text/html; charset=utf-8' 
Response:
  code: 200
  body: '<!DOCTYPE html><html style="font-size:initial"><head><meta charSet="utf-8"/><meta name="baidu-site-verification" content="code-G5HmRz7LQc"/><meta name="description" content="百度开发者中心是一个面向开发者的知识分享平台，专注于为开发者打造一个有温度的技术交流社区，开发者通过平台来分享知识、相互交流。"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="shortcut icon" href="https://developer-resource.bj.bcebos.com/images/developerLogo.ico"/><title>热门问题-技术问答-百度开发者中心-汇聚开放、助力、共赢</title><meta name="keywords" content="DurOS,超级链,API商城,百度网盘开放平台,百度地图开放平台,百度开发者中心,论坛,社区"/><meta name="next-head-count" content="7"/><link rel="preload" href="https://bce.bdstatic.com/developer-server/online/_next/static/css/7ea58671f4422d96f12a.css" ...

**Comment by Bobholamovic** [comment]
你好，由于手头没有可用的Windows机器，我在Linux机器上使用Python 3.9.7环境+最新的稳定版erniebot 0.3.1尝试复现这个问题，但未能复现。

建议在脚本起始位置添加如下代码：

```python
from erniebot.utils.logging import logger
logger.set_level("DEBUG")
```

然后重新执行脚本。我们可以根据程序输出的调试信息一起排查一下这个问题～

**Comment by kuaizilh** [comment]
[报错信息.txt](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/files/12852465/default.txt)
[log信息.txt](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/files/12852466/log.txt)
报错信息以及log如上。是否预期返回文件格式不是text/html格式

**Comment by Bobholamovic** [comment]
在实现上，`erniebot.Image.create` API会首先发起绘图请求，然后轮询直到绘图完成。从`log信息.txt`中可以看出“发起绘图请求”的步骤没有问题，那么可以推断应该是轮询的步骤出现了错误。不过我在两个txt文件中并没有找到轮询请求的时候对应的调试信息，辛苦也贴出一下吧～

**Comment by kuaizilh** [comment]
[capture.md](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/files/12853327/capture.md)
上面是所有日志的截图，貌似没有轮询请求的日志

**Comment by Bobholamovic** [comment]
![image](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/assets/21275753/e0bd9e03-9dc4-4481-a911-40803f1b6bb4)

我这边看不到你的本地路径～ 请把贴图直接复制到issue回复里吧

**Comment by kuaizilh** [comment]
> ![image](https://user-images.githubusercontent.com/21275753/274123931-e0bd9e03-9dc4-4481-a911-40803f1b6bb4.png)
> 
> 我这边看不到你的本地路径～ 请把贴图直接复制到issue回复里吧

[报错截图.zip](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/files/12864178/default.zip)
直接传图一直出错，现在转为zip格式上传。

**Comment by Bobholamovic** [comment]
截图中好像还是没有完整的报错信息，有可能是被IDE截断了。不过，我们尝试在Windows+Python3.9.7环境跑你提供的代码，但仍然未能复现问题。结果如下：

![image](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/assets/21275753/63694c2c-28b2-42dd-bac8-031b417f6eed)
![image](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/assets/21275753/d67439d5-3b64-4694-9190-6d86d01c9c71)

因此，问题可能和你本地的网络配置有关。我建议尝试如下步骤：

1. 首先尝试绕过IDE、在命令行中直接执行脚本。如果这个步骤成功，说明这个问题由IDE导致；如果失败，也可以获取到完整的报错信息。
2. 命令行执行脚本依然不成功，可能需要根据报错信息确认是否是DNS设置等原因导致的。

**Comment by kuaizilh** [comment]
> 截图中好像还是没有完整的报错信息，有可能是被IDE截断了。不过，我们尝试在Windows+Python3.9.7环境跑你提供的代码，但仍然未能复现问题。结果如下：
> 
> ![image](https://user-images.githubusercontent.com/21275753/274207814-63694c2c-28b2-42dd-bac8-031b417f6eed.png) ![image](https://user-images.githubusercontent.com/21275753/274207987-d67439d5-3b64-4694-9190-6d86d01c9c71.png)
> 
> 因此，问题可能和你本地的网络配置有关。我建议尝试如下步骤：
> 
> 1. 首先尝试绕过IDE、在命令行中直接执行脚本。如果这个步骤成功，说明这个问题由IDE导致；如果失败，也可以获取到完整的报错信息。
> 2. 命令行执行脚本依然不成功，可能需要根据报错信息确认是否是DNS设置等原因导致的。

通过命令行执行也是一样的，也是没有更多的报错信息。能否远程直接在我环境上看看？我试过两台windows的机子都是这个报错。
[命令行报错.zip](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/files/12867601/default.zip)

**Comment by Bobholamovic** [comment]
> 能否远程直接在我环境上看看

好的，我们可以通过邮箱沟通。

**Comment by Bobholamovic** [comment]
经远程调试发现该问题系access token无效导致。
