### ISSUE TITLE
在linux下无法安装SDK库的依赖

### ISSUE THREAD

**Issue by fangfangssj** [PaddlePaddle/ERNIE-SDK#48]
![2KZDA1AOS{C1V0Q3R0KSQ_8](https://github.com/PaddlePaddle/ERNIE-Bot-SDK/assets/99968055/0b3f7610-9885-45b7-9344-07703d8672c8)
系统环境如图所示
使用pip安装时没有对应的包

**Comment by Bobholamovic** [comment]
请提供具体的报错信息，例如缺少的依赖情况～
