### ISSUE TITLE
我想知道怎么微调它。

### ISSUE THREAD

**Issue by CQxiaocaimi** [PaddlePaddle/ERNIE-SDK#62]
如题，我真的很想知道，可以Lora微调吗，数据集格式是什么样。
我打算在对话中调用文生图功能，这个可以训练吧。

**Comment by Bobholamovic** [comment]
你好，目前暂不支持微调文生图模型～

**Comment by CQxiaocaimi** [comment]
> 你好，目前暂不支持微调文生图模型～

有没有这个计划呢，另外它还支持图生图吧

**Comment by Bobholamovic** [comment]
目前没有这个计划。当前文生图API不支持传入参考图像～

**Comment by CQxiaocaimi** [comment]
> 目前没有这个计划。当前文生图API不支持传入参考图像～

是这样的，我想通过erniebot-sdk构建应用，但现在的问题是我想基于自己的图像数据集给文心一言，想让它学习，但是目前没有找到这种方法。
所以，文心一言会有类似GPTS、autogen、Xagent这些可基于自然语言交互方式开发应用的方法吗，这样对一些特殊的应用很有帮助，对普通人参与到文心一言扩展也很有帮助。
我从事电商，非常希望能找到真正的多模态应用，不止是文生图，而是图生图、图像风格转换这类。

**Comment by Bobholamovic** [comment]
感谢你的关注和建议～ 请问方便留一个邮箱或者其他联系方式嘛？我们在意你的需求，希望能够更深入了解一下，也便于后续跟进开发相关功能～

**Comment by CQxiaocaimi** [comment]
> 感谢你的关注和建议～ 请问方便留一个邮箱或者其他联系方式嘛？我们在意你的需求，希望能够更深入了解一下，也便于后续跟进开发相关功能～
可以的，邮箱是95014898@qq.com，或者可以添加微信：yh95014898

**Comment by oukohou** [comment]
真有创意，同问定制GPTs相关的计划吗，还是只能手动在message里加prompt

**Comment by Bobholamovic** [comment]
> 真有创意，同问定制GPTs相关的计划吗，还是只能手动在message里加prompt

我们正在开发agent相关功能，欢迎关注！

**Comment by itagan** [comment]
ernie-bot agent框架已推出，也可以在AI studio体验，https://aistudio.baidu.com/application/center?tag=agent

**Comment by itagan** [comment]
> 目前没有这个计划。当前文生图API不支持传入参考图像～

https://ai.baidu.com/ai-doc/NLP/1lg53dryv   文档目前提到，API已支持上次参考图了

**Comment by itagan** [comment]
> 目前没有这个计划。当前文生图API不支持传入参考图像～

https://ai.baidu.com/ai-doc/NLP/1lg53dryv 文档目前提到，API已支持上传参考图了
