### ISSUE TITLE
想咨询下输入最大长度只有4800吗？

### ISSUE THREAD

**Issue by longranger2** [PaddlePaddle/ERNIE-SDK#80]
<img width="1261" alt="image" src="https://github.com/PaddlePaddle/ERNIE-Bot-SDK/assets/52858395/f5c08b39-5a62-402f-b6d4-d729e556661e">

**Comment by Bobholamovic** [comment]
你好，如果需要更高的token数上限，请使用`ernie-bot-8k`模型。

**Comment by qqeip** [comment]
ernie-bot-turbo模型 返回的数据不完整 只有一半信息

**Comment by qqeip** [comment]
好象 更新到0.4.0版本 用stream=True数据完整

**Comment by longranger2** [comment]
好的，我去试试，感谢🌹
